# Chapter 6: Building Your First Deep Neural Network: Introduction to Backpropagation

Chapter 6 merupakan tahap ketika neural network pertama yang benar-benar "deep" mulai dibangun.

Pada chapter sebelumnya:
- Kita sudah belajar gradient descent.
- Kita sudah belajar memperbarui banyak weight.

Pada chapter ini:
- Kita menggabungkan konsep tersebut menjadi deep neural network.
- Kita mempelajari backpropagation.

Materi:
- The streetlight problem
- Preparing the data
- Matrix relationship
- Building a neural network
- Learning the whole dataset
- Full, batch, dan stochastic gradient descent
- Neural networks learn correlation
- Backpropagation
- Linear vs nonlinear

# 1. The Streetlight Problem

Chapter ini menggunakan ilustrasi masalah lampu jalan.

Tujuan:
Membuat neural network belajar hubungan antara kondisi input dan output.

Konsepnya:

Input data → Neural Network → Prediction

Kemudian model membandingkan prediksi dengan jawaban sebenarnya dan memperbaiki weight.

# 2. Representasi Data dengan Matrix

Pada neural network yang lebih besar, data tidak lagi berupa satu angka.

Data direpresentasikan sebagai matrix.

Contoh:

Input:
- beberapa data
- beberapa fitur

Weight:
- hubungan antara input dan neuron

In [1]:
import numpy as np

# contoh input matrix

inputs = np.array([
    [1,0,1],
    [0,1,1],
    [1,1,0]
])

print("Input:")
print(inputs)

Input:
[[1 0 1]
 [0 1 1]
 [1 1 0]]


# 3. Hubungan Input dan Weight

Neural network menghitung hubungan antara input dan weight menggunakan perkalian matrix.

Rumus:

output = input × weight

Operasi matrix memungkinkan neural network menghitung banyak hubungan sekaligus.

In [2]:
inputs = np.array([
    [1,0,1],
    [0,1,1],
    [1,1,0]
])

weights = np.array([
    [0.2,0.3],
    [0.4,0.5],
    [0.6,0.7]
])


output = np.dot(inputs, weights)

print(output)

[[0.8 1. ]
 [1.  1.2]
 [0.6 0.8]]


# 4. Membangun Neural Network

Neural network sederhana terdiri dari:

Input Layer
↓
Hidden Layer
↓
Output

Setiap koneksi antar neuron memiliki weight.

Weight inilah yang dipelajari selama training.

In [3]:
# neural network sederhana satu layer

def neural_network(input_data, weights):
    return np.dot(input_data, weights)


input_data = np.array([1,2,3])

weights = np.array([
    [0.1],
    [0.2],
    [0.3]
])


prediction = neural_network(input_data, weights)

print("Prediction:")
print(prediction)

Prediction:
[1.4]


# 5. Learning Whole Dataset

Pada deep learning, model biasanya tidak belajar dari satu data saja.

Training dilakukan menggunakan seluruh dataset.

Alur:

Dataset
↓
Prediction
↓
Error
↓
Update Weight
↓
Repeat

In [4]:
inputs = np.array([
    [1,2],
    [2,3],
    [3,4]
])

targets = np.array([
    5,
    7,
    9
])

print("Jumlah data:", len(inputs))

Jumlah data: 3


# 6. Full, Batch, dan Stochastic Gradient Descent

Terdapat beberapa cara menggunakan data saat training:

## Full Gradient Descent
Menggunakan seluruh dataset dalam satu update.

## Batch Gradient Descent
Menggunakan sebagian dataset.

## Stochastic Gradient Descent
Menggunakan satu data setiap update.

Perbedaannya adalah kecepatan dan kestabilan proses belajar.

# 7. Neural Network Belajar Korelasi

Neural network tidak memahami arti data seperti manusia.

Neural network mempelajari pola hubungan statistik antar data.

Weight menunjukkan seberapa kuat hubungan tersebut.

In [5]:
# contoh korelasi sederhana

x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

correlation = np.corrcoef(x,y)

print(correlation)

[[1. 1.]
 [1. 1.]]


# 8. Backpropagation

Backpropagation adalah metode untuk mengirimkan error kembali melalui jaringan.

Tujuan:
Menentukan weight mana yang perlu diperbaiki dan seberapa besar perubahannya.

Alur:

Forward propagation:
Input → Output

Backward propagation:
Error → Update weight

In [6]:
# ilustrasi sederhana backpropagation

prediction = 4
target = 10

error = target - prediction

learning_rate = 0.1

weight_change = error * learning_rate

print("Error:", error)
print("Weight change:", weight_change)

Error: 6
Weight change: 0.6000000000000001


# 9. Linear vs Nonlinear

Jika semua layer hanya melakukan operasi linear,
jaringan tidak dapat mempelajari pola kompleks.

Deep neural network membutuhkan nonlinearitas agar mampu memodelkan hubungan yang lebih rumit.

# 10. Deep Neural Network Pertama

Gabungan konsep:

- Multiple weights
- Matrix multiplication
- Gradient descent
- Backpropagation

membentuk deep neural network pertama.

In [7]:
# contoh dua layer sederhana

input_data = np.array([1,2,3])

layer1_weights = np.array([
    [0.1,0.2],
    [0.3,0.4],
    [0.5,0.6]
])

layer1 = np.dot(input_data, layer1_weights)

layer2_weights = np.array([
    [0.7],
    [0.8]
])

output = np.dot(layer1, layer2_weights)

print("Final output:")
print(output)

Final output:
[3.78]


# 11. Kesimpulan Chapter 6

Pada chapter ini kita mempelajari:

1. Neural network dapat dibangun menggunakan matrix.
2. Banyak weight dapat diproses secara bersamaan.
3. Deep neural network terdiri dari beberapa layer.
4. Gradient descent digunakan untuk memperbaiki weight.
5. Backpropagation mengirim error kembali untuk menentukan perubahan weight.
6. Neural network belajar berdasarkan korelasi dalam data.

Chapter berikutnya akan membahas cara memvisualisasikan neural network agar lebih mudah dipahami.